### ISSUE TITLE
Request for Improvement: Enhancing Multi-threaded Port Scanning

### ISSUE THREAD

**Issue by IAmWritingRust** [IAmWritingRust/port-sniffer#1]
I'm seeking your expertise to enhance the functionality of our open-source repository related to multi-threaded port scanning. Currently, we have a basic implementation, but I believe there is room for improvement.
I kindly request your assistance in refining our multi-threaded port scanning capabilities.
Thanks for your valuable contributions!

**Comment by techjoy-dev** [comment]
Assign it to me. I can do it.

**Comment by IAmWritingRust** [comment]
Thank you for your contribution
